//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.05 at 07:34:28 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://personal.com/projects/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.personal.projects.SOAP_Rock_Paper_Scissors;
